table BuyerGeo
	lineageTag: 04c03fcc-5832-4df8-a1c2-270b94b6ada4

	column byr_geo_dim_key
		dataType: string
		lineageTag: d80d815d-25eb-4618-a338-2f89c356c92f
		summarizeBy: none
		sourceColumn: byr_geo_dim_key

		annotation SummarizationSetBy = Automatic

	column 'Buyer Region'
		dataType: string
		lineageTag: 425c2648-789b-497d-8709-ebb5ebf12d64
		summarizeBy: none
		sourceColumn: Buyer Region

		annotation SummarizationSetBy = Automatic

	column 'Buyer Sub Region1'
		dataType: string
		lineageTag: ccf6d92b-7582-4cb3-ace5-c2e247ab928f
		summarizeBy: none
		sourceColumn: Buyer Sub Region1

		annotation SummarizationSetBy = Automatic

	column 'Buyer Sub Region2'
		dataType: string
		lineageTag: 23370f31-1adb-4d76-9c12-5ffd7c389bca
		summarizeBy: none
		sourceColumn: Buyer Sub Region2

		annotation SummarizationSetBy = Automatic

	column 'Buyer Sub Region3'
		dataType: string
		lineageTag: fc0262ef-7a2a-4cbb-ab44-c9f98024573a
		summarizeBy: none
		sourceColumn: Buyer Sub Region3

		annotation SummarizationSetBy = Automatic

	column 'Buyer Country'
		dataType: string
		lineageTag: 45fd8583-0e8a-4342-a856-b8395dfc5d11
		summarizeBy: none
		sourceColumn: Buyer Country

		annotation SummarizationSetBy = Automatic

	column 'Buyer SO2 Cd'
		dataType: string
		lineageTag: e5ea1d11-640f-46fb-9336-5ef699829596
		summarizeBy: none
		sourceColumn: Buyer SO2 Cd

		annotation SummarizationSetBy = Automatic

	column 'Buyer SO2 Name'
		dataType: string
		lineageTag: 6ec21b95-9207-47d4-ba30-e48f6518652f
		summarizeBy: none
		sourceColumn: Buyer SO2 Name

		annotation SummarizationSetBy = Automatic

	column 'Buyer Country Code'
		dataType: string
		lineageTag: 908beda1-9146-427b-a8af-13aab22b4e1a
		summarizeBy: none
		sourceColumn: Buyer Country Code

		annotation SummarizationSetBy = Automatic

	column 'Buyer Country WCC'
		dataType: string
		lineageTag: 5c221ae5-d9bf-4fc1-bef3-2087f7e51c6e
		summarizeBy: none
		sourceColumn: Buyer Country WCC

		annotation SummarizationSetBy = Automatic

	column 'Buyer Aruba Sub region1'
		dataType: string
		lineageTag: 422144c2-23af-4b35-b54e-88a5a0e9f784
		summarizeBy: none
		sourceColumn: Buyer Aruba Sub region1

		annotation SummarizationSetBy = Automatic

	column 'Buyer_ Country _Cd'
		dataType: string
		lineageTag: 8a4b5ac9-9ef4-4729-a181-3c6fd06125b7
		summarizeBy: none
		sourceColumn: Buyer_ Country _Cd

		annotation SummarizationSetBy = Automatic

	partition BuyerGeo = m
		mode: import
		source =
				let
				    Source = PowerPlatform.Dataflows(null),
				    Workspaces = Source{[Id="Workspaces"]}[Data],
				    #"5d8ed3c7-bec6-441c-bde7-d79738c0cb8f" = Workspaces{[workspaceId="5d8ed3c7-bec6-441c-bde7-d79738c0cb8f"]}[Data],
				    #"5e14a931-be12-4446-a815-6af3387eaefa" = #"5d8ed3c7-bec6-441c-bde7-d79738c0cb8f"{[dataflowId="5e14a931-be12-4446-a815-6af3387eaefa"]}[Data],
				    BuyerGeo_ = #"5e14a931-be12-4446-a815-6af3387eaefa"{[entity="BuyerGeo",version=""]}[Data],
				    #"Filtered Rows" = Table.SelectRows(BuyerGeo_, each ([Buyer Sub Region1] <> "CHINA" and [Buyer Sub Region1] <> "RUSSIAN FEDERATION"))
				in
				    #"Filtered Rows"

	annotation PBI_ResultType = Exception

