table EndCustomer
	lineageTag: 5dad6cf9-1611-45b2-8d9a-f8323afab9d3

	column 'DEC OPSI ID'
		dataType: int64
		formatString: 0
		lineageTag: aeae50b0-4de1-4384-8c15-3edf6fabd2ae
		summarizeBy: none
		sourceColumn: DEC OPSI ID

		annotation SummarizationSetBy = Automatic

	column 'DEC OPSI Name'
		dataType: string
		lineageTag: 185cfacc-3b35-47f4-ba97-1387a9e6b9d5
		summarizeBy: none
		sourceColumn: DEC OPSI Name

		annotation SummarizationSetBy = Automatic

	column 'HPE Sales Coverage Segment'
		dataType: string
		lineageTag: d62e18b0-a4fa-4813-9d53-e5ac59a30d40
		summarizeBy: none
		sourceColumn: HPE Sales Coverage Segment

		annotation SummarizationSetBy = Automatic

	column 'HPE Sales Coverage Segment group'
		dataType: string
		lineageTag: 21a2c2b7-047d-4ee5-b134-2da1f2daf29f
		summarizeBy: none
		sourceColumn: HPE Sales Coverage Segment group

		annotation SummarizationSetBy = Automatic

	partition EndCustomer = m
		mode: import
		source =
				let
				    Source = PowerPlatform.Dataflows(null),
				    Workspaces = Source{[Id="Workspaces"]}[Data],
				    #"5d8ed3c7-bec6-441c-bde7-d79738c0cb8f" = Workspaces{[workspaceId="5d8ed3c7-bec6-441c-bde7-d79738c0cb8f"]}[Data],
				    #"5e14a931-be12-4446-a815-6af3387eaefa" = #"5d8ed3c7-bec6-441c-bde7-d79738c0cb8f"{[dataflowId="5e14a931-be12-4446-a815-6af3387eaefa"]}[Data],
				    EndCustomer_ = #"5e14a931-be12-4446-a815-6af3387eaefa"{[entity="EndCustomer",version=""]}[Data],
				    #"Filtered Rows" = Table.SelectRows(EndCustomer_, each ([DEC OPSI ID] <> "-1" and [DEC OPSI ID] <> null and [DEC OPSI ID] <> "") and ([REC Country] <> "CHINA" and [REC Country] <> "RUSSIAN FEDERATION")),
				    #"Removed Other Columns" = Table.SelectColumns(#"Filtered Rows",{"DEC OPSI ID", "DEC OPSI Name", "HPE Sales Coverage Segment", "HPE Sales Coverage Segment group"}),
				    #"Removed Duplicates" = Table.Distinct(#"Removed Other Columns"),
				    #"Changed Type" = Table.TransformColumnTypes(#"Removed Duplicates",{{"DEC OPSI ID", Int64.Type}}),
				    #"Replaced Errors" = Table.ReplaceErrorValues(#"Changed Type", {{"DEC OPSI ID", null}}),
				    #"Filtered Rows1" = Table.SelectRows(#"Replaced Errors", each [DEC OPSI ID] <> null and [DEC OPSI ID] <> ""),
				    #"Removed Duplicates1" = Table.Distinct(#"Filtered Rows1", {"DEC OPSI ID"})
				in
				    #"Removed Duplicates1"

	annotation PBI_ResultType = Table

