table BuyerPartner
	lineageTag: 75f32c66-e7dd-4b9e-94b5-7fff834ae61d

	column byr_ptnr_dim_key
		dataType: string
		lineageTag: c9444bcf-ed15-4741-95a2-12bca359120c
		summarizeBy: none
		sourceColumn: byr_ptnr_dim_key

		annotation SummarizationSetBy = Automatic

	column 'Buyer Siebel HQ PPID'
		dataType: string
		lineageTag: d6811027-e5c7-4b52-9cac-cfa641fac54d
		summarizeBy: none
		sourceColumn: Buyer Siebel HQ PPID

		annotation SummarizationSetBy = Automatic

	column 'Buyer Siebel HQ English Name'
		dataType: string
		lineageTag: d9a77b59-509e-4e35-9b0e-b3f3258856af
		summarizeBy: none
		sourceColumn: Buyer Siebel HQ English Name

		annotation SummarizationSetBy = Automatic

	column 'Buyer Siebel HQ Location ID'
		dataType: string
		lineageTag: 457c3839-68d1-4554-be95-e0edd180c113
		summarizeBy: none
		sourceColumn: Buyer Siebel HQ Location ID

		annotation SummarizationSetBy = Automatic

	column 'Buyer WW Membership'
		dataType: string
		lineageTag: 19ee0012-0496-4200-b078-0d8478b95993
		summarizeBy: none
		sourceColumn: Buyer WW Membership

		annotation SummarizationSetBy = Automatic

	column 'Buyer WW Membership Group'
		dataType: string
		lineageTag: 8c028034-4c23-4c98-aea5-68d02e462223
		summarizeBy: none
		sourceColumn: Buyer WW Membership Group

		annotation SummarizationSetBy = Automatic

	column 'Buyer Region HC Membership'
		dataType: string
		lineageTag: b2ed2418-416d-4d05-81be-ecf86e999381
		summarizeBy: none
		sourceColumn: Buyer Region HC Membership

		annotation SummarizationSetBy = Automatic

	column 'Buyer Original HC Membership'
		dataType: string
		lineageTag: 43e290f0-582e-4b11-b389-d1af3f429751
		summarizeBy: none
		sourceColumn: Buyer Original HC Membership

		annotation SummarizationSetBy = Automatic

	column 'Buyer HC Membership'
		dataType: string
		lineageTag: 808b8cfb-6c62-4dad-b25d-cfaf5bc00323
		summarizeBy: none
		sourceColumn: Buyer HC Membership

		annotation SummarizationSetBy = Automatic

		annotation __PBI_SemanticLinks = [{"LinkTarget":{"TableName":"BuyerPartner","TableItemName":"Buyer HC Membership (groups)","ObjectType":4},"LinkType":"UsedInGroup"}]

	column 'Buyer Siebel Location ID'
		dataType: string
		lineageTag: 58616b38-4e9b-4901-8d43-cfd57385fd01
		summarizeBy: none
		sourceColumn: Buyer Siebel Location ID

		annotation SummarizationSetBy = Automatic

	column 'Buyer Siebel PPID'
		dataType: string
		lineageTag: 45a6b178-c369-429d-9bd6-2bb30af6d40d
		summarizeBy: none
		sourceColumn: Buyer Siebel PPID

		annotation SummarizationSetBy = Automatic

	column 'Buyer Siebel Name'
		dataType: string
		lineageTag: 8a412a04-55a3-4e81-8291-935ecc08bf92
		summarizeBy: none
		sourceColumn: Buyer Siebel Name

		annotation SummarizationSetBy = Automatic

	column 'Buyer Siebel HQ Name'
		dataType: string
		lineageTag: 26641aef-aed9-419f-ac3e-0f39d66d8c71
		summarizeBy: none
		sourceColumn: Buyer Siebel HQ Name

		annotation SummarizationSetBy = Automatic

	column 'Buyer Distri Coverage Metric'
		dataType: string
		lineageTag: 0c0b7877-4f02-4d2d-b680-6139a1e88cac
		summarizeBy: none
		sourceColumn: Buyer Distri Coverage Metric

		annotation SummarizationSetBy = Automatic

	column 'Buyer External Distri Coverage Aruba'
		dataType: string
		lineageTag: 613c9aa3-295a-421f-b4eb-ba3d038d1739
		summarizeBy: none
		sourceColumn: Buyer External Distri Coverage Aruba

		annotation SummarizationSetBy = Automatic

	column 'Buyer External Distri Coverage HIT'
		dataType: string
		lineageTag: 56ed6d4e-34b2-4d9c-b01e-87822666b1d0
		summarizeBy: none
		sourceColumn: Buyer External Distri Coverage HIT

		annotation SummarizationSetBy = Automatic

	column 'Buyer Partner Type'
		dataType: string
		lineageTag: fcb9674c-3a52-47da-9925-53bf77779229
		summarizeBy: none
		sourceColumn: Buyer Partner Type

		annotation SummarizationSetBy = Automatic

	column 'Buyer HQ Channel Segment Cd'
		dataType: string
		lineageTag: ec819e13-6548-4434-9400-a133359c2d95
		summarizeBy: none
		sourceColumn: Buyer HQ Channel Segment Cd

		annotation SummarizationSetBy = Automatic

	column 'Buyer HQ Channel Segment'
		dataType: string
		lineageTag: 87e64010-fbdd-4eec-a645-f159e9410375
		summarizeBy: none
		sourceColumn: Buyer HQ Channel Segment

		annotation SummarizationSetBy = Automatic

	column 'Byr Extnl Dist Cvrg PN'
		dataType: string
		lineageTag: 65305be4-71bd-4b89-b924-5e590119ba05
		summarizeBy: none
		sourceColumn: Byr Extnl Dist Cvrg PN

		annotation SummarizationSetBy = Automatic

	column 'Buyer Siebel Regional PPID'
		dataType: string
		lineageTag: 4bf7d9ab-e2b8-47c5-a986-d393dcb8375f
		summarizeBy: none
		sourceColumn: Buyer Siebel Regional PPID

		annotation SummarizationSetBy = Automatic

	column 'Buyer Siebel Regional Name'
		dataType: string
		lineageTag: bd20af30-e0f1-4776-922c-d10c8176a3a5
		summarizeBy: none
		sourceColumn: Buyer Siebel Regional Name

		annotation SummarizationSetBy = Automatic

	column 'Buyer Region Aruba Membership'
		dataType: string
		lineageTag: d5b0c577-b3c4-4ff5-b55b-bd4b7cc80d4c
		summarizeBy: none
		sourceColumn: Buyer Region Aruba Membership

		annotation SummarizationSetBy = Automatic

	column 'Buyer Cvrg Size Segment'
		dataType: string
		lineageTag: 527849b0-a5e2-47cb-934f-efa73b5f5bc0
		summarizeBy: none
		sourceColumn: Buyer Cvrg Size Segment

		annotation SummarizationSetBy = Automatic

	column 'Buyer HC Membership (groups)' =
			SWITCH(
				TRUE,
				ISBLANK('BuyerPartner'[Buyer HC Membership]),
				"(Blank)",
				'BuyerPartner'[Buyer HC Membership] IN {" GOLD PARTNER",
					" PLATINUM PARTNER"},
				"PG",
				'BuyerPartner'[Buyer HC Membership] IN {" BUSINESS PARTNER",
					" SILVER PARTNER",
					"HC Proximity"},
				"SBP",
				'BuyerPartner'[Buyer HC Membership]
			)
		dataType: string
		lineageTag: 1712b038-407e-43d6-84d2-25995866b3b2
		summarizeBy: none
		isDataTypeInferred

		extendedProperty GroupingMetadata =
				{
				  "version": 0,
				  "groupedColumns": [
				    {
				      "Column": {
				        "Expression": {
				          "SourceRef": {
				            "Entity": "BuyerPartner"
				          }
				        },
				        "Property": "Buyer HC Membership"
				      }
				    }
				  ]
				}

		annotation GroupingDesignState = {"Version":0,"Sources":[{"Name":"b","Entity":"BuyerPartner"}],"GroupedColumns":[{"Column":{"Expression":{"SourceRef":{"Source":"b"}},"Property":"Buyer HC Membership"}}],"GroupItems":[{"DisplayName":"(Blank)","BlankDefaultPlaceholder":true},{"DisplayName":"PG","Expression":{"In":{"Expressions":[{"Column":{"Expression":{"SourceRef":{"Source":"b"}},"Property":"Buyer HC Membership"}}],"Values":[[{"Literal":{"Value":"' GOLD PARTNER'"}}],[{"Literal":{"Value":"' PLATINUM PARTNER'"}}]]}}},{"DisplayName":"SBP","Expression":{"In":{"Expressions":[{"Column":{"Expression":{"SourceRef":{"Source":"b"}},"Property":"Buyer HC Membership"}}],"Values":[[{"Literal":{"Value":"' BUSINESS PARTNER'"}}],[{"Literal":{"Value":"' SILVER PARTNER'"}}],[{"Literal":{"Value":"'HC Proximity'"}}]]}}}]}

		annotation SummarizationSetBy = Automatic

	partition BuyerPartner = m
		mode: import
		source =
				let
				    Source = PowerPlatform.Dataflows(null),
				    Workspaces = Source{[Id="Workspaces"]}[Data],
				    #"5d8ed3c7-bec6-441c-bde7-d79738c0cb8f" = Workspaces{[workspaceId="5d8ed3c7-bec6-441c-bde7-d79738c0cb8f"]}[Data],
				    #"5e14a931-be12-4446-a815-6af3387eaefa" = #"5d8ed3c7-bec6-441c-bde7-d79738c0cb8f"{[dataflowId="5e14a931-be12-4446-a815-6af3387eaefa"]}[Data],
				    BuyerPartner_ = #"5e14a931-be12-4446-a815-6af3387eaefa"{[entity="BuyerPartner",version=""]}[Data],
				   #"Removed Other Columns" = Table.SelectColumns(BuyerPartner_,{"byr_ptnr_dim_key", "Buyer Siebel PPID", "Buyer Siebel Name", "Buyer Siebel HQ PPID", "Buyer Siebel HQ Name", "Buyer Siebel HQ English Name", "Buyer Siebel HQ Location ID", "Buyer Siebel Location ID", "Buyer Distri Coverage Metric", "Buyer External Distri Coverage Aruba", "Buyer External Distri Coverage HIT", "Buyer Partner Type", "Buyer WW Membership", "Buyer WW Membership Group", "Buyer HQ Channel Segment Cd", "Buyer HQ Channel Segment", "Byr Extnl Dist Cvrg PN", "Buyer Region HC Membership", "Buyer Original HC Membership", "Buyer Siebel Regional PPID", "Buyer Siebel Regional Name", "Buyer Region Aruba Membership", "Buyer Cvrg Size Segment"}),
				    #"Added Custom" = Table.AddColumn(#"Removed Other Columns", "Buyer HC Membership", each Text.Replace([Buyer Region HC Membership], "PARTNER READY", "")),
				    #"Changed Type" = Table.TransformColumnTypes(#"Added Custom",{{"Buyer HC Membership", type text}}),
				   #"Replaced Value" = Table.ReplaceValue(#"Changed Type",each [Buyer Siebel HQ PPID],each if List.Contains({"3-VJJMX7","3-V9WXAM"},[Buyer Siebel HQ PPID]) then "3-VB1WB7" else [Buyer Siebel HQ PPID],
				    Replacer.ReplaceValue,{"Buyer Siebel HQ PPID"}),
				    #"Replaced Value1" = Table.ReplaceValue(#"Replaced Value",each [Buyer Siebel HQ English Name],each if List.Contains({"3-VJJMX7","3-V9WXAM","3-VB1WB7"},[Buyer Siebel HQ PPID]) then "Componentes el Orbe S A (Group)"
				     else [Buyer Siebel HQ English Name],Replacer.ReplaceValue,{"Buyer Siebel HQ English Name"}),
				    #"Replaced Value2" = Table.ReplaceValue(#"Replaced Value1",each [Buyer Siebel HQ PPID],each if List.Contains({"3-WFV16V","3-Z6BLZ5"},[Buyer Siebel HQ PPID]) then "3-Z5TZQ1" else [Buyer Siebel HQ PPID],
				    Replacer.ReplaceValue,{"Buyer Siebel HQ PPID"}),
				    #"Replaced Value3" = Table.ReplaceValue(#"Replaced Value2",each [Buyer Siebel HQ English Name],each if List.Contains({"3-WFV16V","3-Z6BLZ5","3-Z5TZQ1"},[Buyer Siebel HQ PPID]) then "MT2005 Sociedad Anonima De Capital Variable (Group)"
				     else [Buyer Siebel HQ English Name],Replacer.ReplaceValue,{"Buyer Siebel HQ English Name"}),
				    #"Replaced Value4" = Table.ReplaceValue(#"Replaced Value3",each [Buyer Siebel HQ PPID],each if List.Contains({"3-5L9-1384","3-5L9-785"},[Buyer Siebel HQ PPID]) then "3-5L9-784" else [Buyer Siebel HQ PPID],
				    Replacer.ReplaceValue,{"Buyer Siebel HQ PPID"}),
				    #"Replaced Value5" = Table.ReplaceValue(#"Replaced Value4",each [Buyer Siebel HQ English Name],each if List.Contains({"3-5L9-1384","3-5L9-785","3-5L9-784"},[Buyer Siebel HQ PPID]) then "Sonda SA Chile (Group)"
				     else [Buyer Siebel HQ English Name],Replacer.ReplaceValue,{"Buyer Siebel HQ English Name"}),
				    #"Replaced Value6" = Table.ReplaceValue(#"Replaced Value5",each [Buyer Siebel HQ PPID],each if List.Contains({"3-J6S9UT","3-UZ4JYZ","3-3P5WRW"},[Buyer Siebel HQ PPID]) then "3-5L9-578" else [Buyer Siebel HQ PPID],
				    Replacer.ReplaceValue,{"Buyer Siebel HQ PPID"}),
				    #"Replaced Value7" = Table.ReplaceValue(#"Replaced Value6",each [Buyer Siebel HQ English Name],each if List.Contains({"3-J6S9UT","3-UZ4JYZ","3-3P5WRW","3-5L9-578"},[Buyer Siebel HQ PPID]) then "Tecnologia Aplicada Sa Tecnasa (Group)"
				     else [Buyer Siebel HQ English Name],Replacer.ReplaceValue,{"Buyer Siebel HQ English Name"})
				in
				    #"Replaced Value7"

	annotation PBI_ResultType = Table

